---
name: Geo-Hex
version: v0.0.1
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Convert between latitude/longitude and GeoHex code
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  Math::Round: 0
  POSIX: 0
  Test::Base: 0
  version: 0
configure_requires:
  Module::Build: 0.35
provides:
  Geo::Hex:
    file: lib/Geo/Hex.pm
    version: v0.0.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
